# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('head_img', models.ImageField(null=True, upload_to='head_img')),
                ('account', models.CharField(max_length=32, null=True)),
                ('passwd', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
