# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
