# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171203_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='passinger', max_length=32)),
                ('userimg', models.ImageField(null=True, upload_to='head_img')),
                ('blog_id', models.IntegerField()),
                ('comment_id', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
