# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='userimg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='head_img',
        ),
        migrations.AddField(
            model_name='comments',
            name='userimage',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
