# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171212_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image_url',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
