# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image_url',
        ),
    ]
