# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comments_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
