# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
